### ISSUE TITLE
Can I run this in windows?

### ISSUE THREAD

**Issue by Abdify** [MuktadirHassan/custom-shell#1]
![image](https://github.com/MuktadirHassan/custom-shell/assets/67672693/f98b40b1-b60c-4a82-a315-0ad0c34a88ed)

**Comment by MuktadirHassan** [comment]
@Abdify No bro, unfortunately it's not a complete project. There are a few major features missing. Like history and tab completion. and it will not work on windows as windows uses different libraries than gnu/linux project.
